version: "3"
services:

  xmssql:
    build:
      context: ./src/db/build
      args:
        sapw: "!tHePA55!"
    ports:
      - "1433:1433"
    volumes:
      - "leaf-mssql:/var/opt/mssql"
    networks:
      local:
        aliases:
          - xmssql
  
 #xcoreapi:
 #   build: 
 #     context: ./src/server
 #     dockerfile: ./src/server/Dockerfile
 #   ports:
 #     - "5001:5001"
 #   depends_on:
 #     - xmssql
 #   volumes:
 #     - ./src/server:/app
 #     - ${KEYS}:/.keys
 #     - ${SERILOG_DIR}:/logs
 #   environment:
 #     LEAF_JWT_CERT: ${LEAF_JWT_CERT}
 #     LEAF_JWT_KEY: ${LEAF_JWT_KEY}
 #     LEAF_JWT_KEY_PW: ${LEAF_JWT_KEY_PW}
 #     LEAF_APP_DB: ${LEAF_APP_DB}
 #     LEAF_CLIN_DB: ${LEAF_CLIN_DB}
 #     SERILOG_DIR: /logs
 #   working_dir: "/app/API"
 #   command: ["dotnet", "run"]
 #   networks:
 #     local:
 #       aliases:
 #         - xcoreapi

 #xnode:
 #   build: ./src/ui-client
 #   ports:
 #     - "3000:3000"
 #   depends_on:
 #     - xmssql
 #     - xcoreapi
 #   working_dir: /app
 #   networks:
 #     local:
 #       aliases:
 #         - xnode

volumes:
  leaf-mssql:           

networks:
  local:
    driver: bridge


# ==DB==
# docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Th3PA55--8zz' -p 1433:1433 --name leaf_db_test mcr.microsoft.com/mssql/server:2017-latest 
# sleep 10s
# sqlcmd -S '127.0.0.1,1433' -U SA -P 'Th3PA55--8zz' -i src/db/build/LeafDB.sql 
# sqlcmd -S '127.0.0.1,1433' -U SA -P 'Th3PA55--8zz' -d LeafDB -i src/db/build/LeafDB.Init.sql

# ==API==
# docker build -f src/server/Dockerfile -t leaf_api .
# docker run -d -e 'LEAF_APP_DB=Server=localhost;Database=LeafDB;uid=sa;Password=Th3PA55--8zz' -e 'LEAF_CLIN_DB=${LEAF_CLIN_DB}' \ 
# -p 5001:5001 --name leaf_api_test